import type { NextPage } from 'next'
import {useRouter} from 'next/router';
import Head from 'next/head'
import styles from '../../styles/Home.module.css';

const Dashboard: NextPage = () => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title> Home | Traveler</title>
        <meta name="description" content="Generated by create next app" />
        <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mainContent}>
       <h1>Dashboard</h1>
      </main>
    
    </div>
  )
}

export default Dashboard;
