import type { GetServerSideProps, NextPage } from 'next'
import {useRouter} from 'next/router';
import Head from 'next/head'
import styles from '../../styles/Home.module.css';
import Places from '../components/Places';
import { parseCookies } from 'nookies';

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title> Home | Traveler</title>
        <meta name="description" content="Generated by create next app" />
        <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mainContent}>
        <section>
          <strong>Viva uma grande aventura</strong>
          <p>Descubra locais incríveis para se visitar em cidades maravilhosas de Santa Catarina.</p>
          <button onClick={() => router.push('/places')} className={styles.callToAction}>Descobrir todos os lugares</button>
        </section>
        <Places />
      </main>
    
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {

  const {traveller_token} = parseCookies(ctx);
  if(!traveller_token) return { props: {} };

  const {token, user} = JSON.parse(traveller_token);
  
  return { redirect: {
    destination: '/dashboard',
    permanent: false,
  } ,props: { token, user } }
}


export default Home
